SERVER_SOURCE_CODE=server.c
CLIENT_SOURCE_CODE=tcp_client.c
SERVER_EXE=server
CLIENT_EXE=subscriber
CFLAGS=-Wall -Wextra -g -o
CC=gcc
HEADER=tools.h
ADDITIONAL_SRCS=common_funcs.c list.c queue.c

server: $(SERVER_SOURCE_CODE) $(HEADER) $(ADDITIONAL_SRCS)
	$(CC) $(SERVER_SOURCE_CODE) $(ADDITIONAL_SRCS) $(CFLAGS) $(SERVER_EXE)

subscriber: $(CLIENT_SOURCE_CODE) $(HEADER) $(ADDITIONAL_SRCS)
	$(CC) $(CLIENT_SOURCE_CODE) $(ADDITIONAL_SRCS) $(CFLAGS) $(CLIENT_EXE)

clean:
	rm -rf $(SERVER_EXE) $(CLIENT_EXE)
